#ifndef __TASK_PRIORITY_H_
#define __TASK_PRIORITY_H_

#define	MAIN_TASK_PRIORITY		(tskIDLE_PRIORITY + 1)
#define	SENSOR_TASK_PRIORITY	(tskIDLE_PRIORITY + 2)
#define	LORA_TASK_PRIORITY		(tskIDLE_PRIORITY + 3)
#define	WIFI_TASK_PRIORITY		(tskIDLE_PRIORITY + 4)

#endif //__TASK_PRIORITY_H_
